import Head from "next/head";
import styles from "../styles/Home.module.css";
import Box from "./../components/Box";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          className="App"
          style={{
            width: 500,
            margin: "0 auto",
            marginTop: "20%",
            maxWidth: 500,
            minHeight: 500,
            display: "flex",
            flexDirection: "row",
            flexWrap: "wrap",
            border: "1px solid #efefef"
          }}
        >
          <Box
            id={"1"}
            name={"John Doe"}
            img={"https://randomuser.me/api/portraits/thumb/men/73.jpg"}
            onClick={() => {}}
            active={true}
          />
          <Box
            id={"1"}
            name={"Jane Doe"}
            img={"https://randomuser.me/api/portraits/thumb/women/73.jpg"}
            onClick={() => {}}
            active={false}
          />
        </div>
      </main>
    </div>
  );
}
